#!/usr/bin/env node

/**
 * Test Reporter for MCP Inspector Testing
 * Generates HTML and JSON reports with screenshots
 */

import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { mkdir, writeFile, readFile } from 'fs/promises';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export class TestReporter {
  constructor(options = {}) {
    this.options = {
      outputDir: options.outputDir || join(__dirname, '../../reports'),
      includeScreenshots: options.includeScreenshots !== false,
      generateHtml: options.generateHtml !== false,
      generateJson: options.generateJson !== false,
      ...options
    };
    
    this.reportTimestamp = new Date().toISOString().replace(/[:.]/g, '-');
  }

  /**
   * Initialize reporter and create output directories
   */
  async initialize() {
    console.log('📊 Initializing test reporter');
    
    try {
      // Create output directories
      await mkdir(this.options.outputDir, { recursive: true });
      await mkdir(join(this.options.outputDir, 'assets'), { recursive: true });
      
      console.log(`✅ Report output directory: ${this.options.outputDir}`);
      return true;
    } catch (error) {
      console.error('❌ Failed to initialize reporter:', error.message);
      throw error;
    }
  }

  /**
   * Generate comprehensive test report
   */
  async generateReport(reportData) {
    console.log('📝 Generating test report...');
    
    try {
      const reports = [];
      
      // Generate JSON report
      if (this.options.generateJson) {
        const jsonPath = await this.generateJsonReport(reportData);
        reports.push({ type: 'json', path: jsonPath });
      }
      
      // Generate HTML report
      if (this.options.generateHtml) {
        const htmlPath = await this.generateHtmlReport(reportData);
        reports.push({ type: 'html', path: htmlPath });
      }
      
      console.log(`✅ Generated ${reports.length} report(s)`);
      return reports;
    } catch (error) {
      console.error('❌ Failed to generate report:', error.message);
      throw error;
    }
  }

  /**
   * Generate JSON report
   */
  async generateJsonReport(reportData) {
    const fileName = `mcp-test-report-${this.reportTimestamp}.json`;
    const filePath = join(this.options.outputDir, fileName);
    
    const jsonReport = {
      ...reportData,
      metadata: {
        generatedAt: new Date().toISOString(),
        reportVersion: '1.0.0',
        generator: 'MCP Inspector Test Framework'
      }
    };
    
    await writeFile(filePath, JSON.stringify(jsonReport, null, 2));
    console.log(`📄 JSON report: ${fileName}`);
    
    return filePath;
  }

  /**
   * Generate HTML report with embedded styles and scripts
   */
  async generateHtmlReport(reportData) {
    const fileName = `mcp-test-report-${this.reportTimestamp}.html`;
    const filePath = join(this.options.outputDir, fileName);
    
    const html = await this.buildHtmlContent(reportData);
    await writeFile(filePath, html);
    
    console.log(`🌐 HTML report: ${fileName}`);
    return filePath;
  }

  /**
   * Build complete HTML report content
   */
  async buildHtmlContent(reportData) {
    const css = this.getReportStyles();
    const js = this.getReportScripts();
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP Inspector Test Report - ${new Date(reportData.timestamp).toLocaleDateString()}</title>
    <style>${css}</style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🔍 MCP Inspector Test Report</h1>
            <div class="header-info">
                <span class="timestamp">Generated: ${new Date(reportData.timestamp).toLocaleString()}</span>
                <span class="environment">Environment: ${reportData.environment.headless ? 'Headless' : 'GUI'}</span>
            </div>
        </header>

        ${this.buildSummarySection(reportData.summary)}
        ${this.buildTestResultsSection(reportData.testResults)}
        ${this.buildEnvironmentSection(reportData.environment)}
        
        <footer class="footer">
            <p>Generated by MCP Inspector Test Framework v1.0.0</p>
        </footer>
    </div>
    
    <script>${js}</script>
</body>
</html>`;
  }

  /**
   * Build summary section HTML
   */
  buildSummarySection(summary) {
    const successRate = summary.successRate || 0;
    const successRateClass = successRate >= 80 ? 'success' : successRate >= 60 ? 'warning' : 'error';
    
    return `
        <section class="summary">
            <h2>📊 Test Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <div class="summary-number">${summary.totalServers}</div>
                    <div class="summary-label">Total Servers</div>
                </div>
                <div class="summary-card ${summary.successfulServers === summary.totalServers ? 'success' : 'error'}">
                    <div class="summary-number">${summary.successfulServers}/${summary.totalServers}</div>
                    <div class="summary-label">Servers Passed</div>
                </div>
                <div class="summary-card">
                    <div class="summary-number">${summary.totalTests}</div>
                    <div class="summary-label">Total Tests</div>
                </div>
                <div class="summary-card ${summary.passedTests === summary.totalTests ? 'success' : 'error'}">
                    <div class="summary-number">${summary.passedTests}/${summary.totalTests}</div>
                    <div class="summary-label">Tests Passed</div>
                </div>
                <div class="summary-card ${successRateClass}">
                    <div class="summary-number">${successRate}%</div>
                    <div class="summary-label">Success Rate</div>
                </div>
            </div>
        </section>`;
  }

  /**
   * Build test results section HTML
   */
  buildTestResultsSection(testResults) {
    const serversHtml = testResults.map(server => this.buildServerSection(server)).join('');
    
    return `
        <section class="test-results">
            <h2>🔧 Server Test Results</h2>
            ${serversHtml}
        </section>`;
  }

  /**
   * Build individual server section HTML
   */
  buildServerSection(server) {
    const statusClass = server.status === 'completed' ? 'success' : 'error';
    const statusIcon = server.status === 'completed' ? '✅' : '❌';
    
    return `
        <div class="server-section">
            <div class="server-header">
                <h3>${statusIcon} ${server.serverName}</h3>
                <span class="server-status ${statusClass}">${server.status}</span>
            </div>
            
            <div class="server-details">
                <div class="capabilities-grid">
                    ${this.buildCapabilityCard('Tools', server.capabilities.tools)}
                    ${this.buildCapabilityCard('Resources', server.capabilities.resources)}
                    ${this.buildCapabilityCard('Prompts', server.capabilities.prompts)}
                </div>
                
                ${server.elicitation?.supported ? this.buildElicitationSection(server.elicitation) : ''}
                ${server.progressNotifications?.supported ? this.buildProgressSection(server.progressNotifications) : ''}
                ${server.ping ? this.buildPingSection(server.ping) : ''}
                ${server.connection ? this.buildConnectionSection(server.connection) : ''}
                ${server.errors.length > 0 ? this.buildErrorsSection(server.errors) : ''}
                ${server.screenshots.length > 0 ? this.buildScreenshotsSection(server.screenshots) : ''}
            </div>
        </div>`;
  }

  /**
   * Build capability card HTML
   */
  buildCapabilityCard(name, capability) {
    const statusClass = capability.actual === capability.expected ? 'success' : 'error';
    const statusIcon = capability.actual === capability.expected ? '✅' : '❌';
    
    return `
        <div class="capability-card ${statusClass}">
            <div class="capability-header">
                <span class="capability-name">${name}</span>
                <span class="capability-status">${statusIcon}</span>
            </div>
            <div class="capability-count">${capability.actual}/${capability.expected}</div>
            ${capability.tests.length > 0 ? this.buildTestsList(capability.tests) : ''}
        </div>`;
  }

  /**
   * Build tests list HTML
   */
  buildTestsList(tests) {
    const testsHtml = tests.map(test => {
      const statusIcon = test.status === 'success' ? '✅' : '❌';
      const responseTime = test.responseTime ? ` (${test.responseTime}ms)` : '';
      
      return `<div class="test-item">
                <span class="test-status">${statusIcon}</span>
                <span class="test-name">${test.name}${responseTime}</span>
              </div>`;
    }).join('');
    
    return `<div class="tests-list">${testsHtml}</div>`;
  }

  /**
   * Build elicitation section HTML
   */
  buildElicitationSection(elicitation) {
    return `
        <div class="feature-section">
            <h4>📝 Elicitation Tests</h4>
            ${this.buildTestsList(elicitation.tests)}
        </div>`;
  }

  /**
   * Build progress notifications section HTML
   */
  buildProgressSection(progress) {
    return `
        <div class="feature-section">
            <h4>📊 Progress Notifications</h4>
            ${this.buildTestsList(progress.tests)}
        </div>`;
  }

  /**
   * Build ping section HTML
   */
  buildPingSection(ping) {
    const statusIcon = ping.status === 'success' ? '✅' : '❌';
    const responseTime = ping.responseTime ? ` (${ping.responseTime}ms)` : '';
    
    return `
        <div class="feature-section">
            <h4>🏓 Ping Test</h4>
            <div class="ping-result">
                <span>${statusIcon} ${ping.status}${responseTime}</span>
            </div>
        </div>`;
  }

  /**
   * Build connection section HTML
   */
  buildConnectionSection(connection) {
    const statusIcon = connection.status === 'success' ? '✅' : '❌';
    
    return `
        <div class="feature-section">
            <h4>🔌 Connection</h4>
            <div class="connection-result">
                <span>${statusIcon} ${connection.status}</span>
                <small>${new Date(connection.timestamp).toLocaleTimeString()}</small>
            </div>
        </div>`;
  }

  /**
   * Build errors section HTML
   */
  buildErrorsSection(errors) {
    const errorsHtml = errors.map(error => `
        <div class="error-item">
            <span class="error-type">${error.type}</span>
            <span class="error-message">${error.message}</span>
            <small class="error-timestamp">${new Date(error.timestamp).toLocaleTimeString()}</small>
        </div>
    `).join('');
    
    return `
        <div class="errors-section">
            <h4>❌ Errors</h4>
            <div class="errors-list">${errorsHtml}</div>
        </div>`;
  }

  /**
   * Build screenshots section HTML
   */
  buildScreenshotsSection(screenshots) {
    const screenshotsHtml = screenshots.map((screenshot, index) => `
        <div class="screenshot-item">
            <img src="${screenshot}" alt="Screenshot ${index + 1}" loading="lazy" onclick="openScreenshot(this.src)">
        </div>
    `).join('');
    
    return `
        <div class="screenshots-section">
            <h4>📸 Screenshots</h4>
            <div class="screenshots-grid">${screenshotsHtml}</div>
        </div>`;
  }

  /**
   * Build environment section HTML
   */
  buildEnvironmentSection(environment) {
    return `
        <section class="environment">
            <h2>🔧 Test Environment</h2>
            <div class="environment-details">
                <div class="env-item">
                    <span class="env-label">Headless Mode:</span>
                    <span class="env-value">${environment.headless ? 'Yes' : 'No'}</span>
                </div>
                <div class="env-item">
                    <span class="env-label">Timeout:</span>
                    <span class="env-value">${environment.timeout}ms</span>
                </div>
                <div class="env-item">
                    <span class="env-label">Retries:</span>
                    <span class="env-value">${environment.retries}</span>
                </div>
            </div>
        </section>`;
  }

  /**
   * Get CSS styles for the report
   */
  getReportStyles() {
    return `
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f7fa;
        }
        
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            text-align: center;
        }
        
        .header h1 { font-size: 2.5rem; margin-bottom: 1rem; }
        .header-info { display: flex; justify-content: center; gap: 2rem; flex-wrap: wrap; }
        .header-info span { background: rgba(255,255,255,0.2); padding: 0.5rem 1rem; border-radius: 20px; }
        
        .summary {
            background: white;
            border-radius: 12px;
            padding: 2rem;
            margin-bottom: 2rem;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .summary h2 { margin-bottom: 1.5rem; color: #4a5568; }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }
        
        .summary-card {
            background: #f8fafc;
            border: 2px solid #e2e8f0;
            border-radius: 8px;
            padding: 1.5rem;
            text-align: center;
            transition: transform 0.2s;
        }
        
        .summary-card:hover { transform: translateY(-2px); }
        .summary-card.success { border-color: #48bb78; background: #f0fff4; }
        .summary-card.warning { border-color: #ed8936; background: #fffaf0; }
        .summary-card.error { border-color: #f56565; background: #fff5f5; }
        
        .summary-number { font-size: 2rem; font-weight: bold; color: #2d3748; }
        .summary-label { color: #718096; font-size: 0.9rem; }
        
        .test-results {
            background: white;
            border-radius: 12px;
            padding: 2rem;
            margin-bottom: 2rem;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .test-results h2 { margin-bottom: 1.5rem; color: #4a5568; }
        
        .server-section {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            margin-bottom: 1.5rem;
            overflow: hidden;
        }
        
        .server-header {
            background: #f8fafc;
            padding: 1rem 1.5rem;
            display: flex;
            justify-content: between;
            align-items: center;
            border-bottom: 1px solid #e2e8f0;
        }
        
        .server-header h3 { color: #2d3748; margin: 0; }
        .server-status { 
            padding: 0.25rem 0.75rem; 
            border-radius: 20px; 
            font-size: 0.8rem; 
            font-weight: bold;
        }
        .server-status.success { background: #c6f6d5; color: #22543d; }
        .server-status.error { background: #fed7d7; color: #742a2a; }
        
        .server-details { padding: 1.5rem; }
        
        .capabilities-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 1.5rem;
        }
        
        .capability-card {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 1rem;
            background: #f8fafc;
        }
        
        .capability-card.success { border-color: #48bb78; background: #f0fff4; }
        .capability-card.error { border-color: #f56565; background: #fff5f5; }
        
        .capability-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 0.5rem;
        }
        
        .capability-name { font-weight: bold; color: #2d3748; }
        .capability-count { font-size: 1.5rem; font-weight: bold; color: #4a5568; margin-bottom: 0.5rem; }
        
        .tests-list { margin-top: 0.5rem; }
        .test-item {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            padding: 0.25rem 0;
            font-size: 0.9rem;
        }
        
        .feature-section { margin-bottom: 1rem; }
        .feature-section h4 { color: #4a5568; margin-bottom: 0.5rem; }
        
        .ping-result, .connection-result {
            display: flex;
            align-items: center;
            gap: 1rem;
            padding: 0.5rem;
            background: #f8fafc;
            border-radius: 4px;
        }
        
        .errors-section { margin-top: 1rem; }
        .error-item {
            background: #fff5f5;
            border: 1px solid #feb2b2;
            border-radius: 4px;
            padding: 0.75rem;
            margin-bottom: 0.5rem;
        }
        
        .error-type { font-weight: bold; color: #742a2a; }
        .error-message { display: block; margin: 0.25rem 0; }
        .error-timestamp { color: #718096; font-size: 0.8rem; }
        
        .screenshots-section { margin-top: 1rem; }
        .screenshots-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 1rem;
        }
        
        .screenshot-item img {
            width: 100%;
            height: 150px;
            object-fit: cover;
            border-radius: 4px;
            cursor: pointer;
            transition: transform 0.2s;
        }
        
        .screenshot-item img:hover { transform: scale(1.05); }
        
        .environment {
            background: white;
            border-radius: 12px;
            padding: 2rem;
            margin-bottom: 2rem;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .environment h2 { margin-bottom: 1.5rem; color: #4a5568; }
        .environment-details { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
        .env-item { display: flex; justify-content: space-between; padding: 0.75rem; background: #f8fafc; border-radius: 4px; }
        .env-label { font-weight: bold; color: #4a5568; }
        .env-value { color: #2d3748; }
        
        .footer {
            text-align: center;
            padding: 2rem;
            color: #718096;
            font-size: 0.9rem;
        }
        
        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.9);
        }
        
        .modal-content {
            margin: auto;
            display: block;
            width: 80%;
            max-width: 700px;
            max-height: 80%;
        }
        
        .close {
            position: absolute;
            top: 15px;
            right: 35px;
            color: #f1f1f1;
            font-size: 40px;
            font-weight: bold;
            cursor: pointer;
        }
        
        @media (max-width: 768px) {
            .container { padding: 10px; }
            .header h1 { font-size: 1.8rem; }
            .header-info { flex-direction: column; gap: 0.5rem; }
            .summary-grid, .capabilities-grid { grid-template-columns: 1fr; }
        }
    `;
  }

  /**
   * Get JavaScript for the report
   */
  getReportScripts() {
    return `
        function openScreenshot(src) {
            const modal = document.createElement('div');
            modal.className = 'modal';
            modal.innerHTML = \`
                <span class="close" onclick="closeModal(this)">&times;</span>
                <img class="modal-content" src="\${src}">
            \`;
            
            document.body.appendChild(modal);
            modal.style.display = 'block';
            
            modal.onclick = function(event) {
                if (event.target === modal) {
                    closeModal(modal.querySelector('.close'));
                }
            };
        }
        
        function closeModal(element) {
            const modal = element.closest('.modal');
            modal.style.display = 'none';
            setTimeout(() => modal.remove(), 300);
        }
        
        // Add keyboard shortcuts
        document.addEventListener('keydown', function(event) {
            if (event.key === 'Escape') {
                const modal = document.querySelector('.modal');
                if (modal) {
                    closeModal(modal.querySelector('.close'));
                }
            }
        });
        
        // Add collapsible sections
        document.addEventListener('DOMContentLoaded', function() {
            const serverHeaders = document.querySelectorAll('.server-header');
            serverHeaders.forEach(header => {
                header.style.cursor = 'pointer';
                header.addEventListener('click', function() {
                    const details = this.nextElementSibling;
                    details.style.display = details.style.display === 'none' ? 'block' : 'none';
                });
            });
        });
    `;
  }
}

export default TestReporter;